apiVersion: v1 # версия API Kubernetes, используемая в манифесте
kind: Secret # тип ресурса, описываемого манифестом
metadata:
  name: my-app-secret # имя Secret
type: Opaque # тип данных, которые хранятся в Secret (в данном случае - произвольные данные)
data:
  api-key: c2VjcmV0LWFwaS1rZXkK # значение переменной окружения api-key, закодированное в формате base64

