---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *" # запускается задание раз в минуту
  concurrencyPolicy: Forbid # запрещается создание конкуретных параллельных подов
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            -  /bin/sh
            -  -c
            -  date; echo Hellow from the Kubernetes cluster
          restartPolicy: Never

          # startingDeadlineSeconds      - если значение не установлено , то в случае сбоя задания если от последнего задания можно было по времени выполнить 100 заданий , то задача после перезауска не запустится.

          # successfulJobsHistoryLimit   - возможность очистки истории подов , по умолчанию 3 последних пода.

