---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  backoffLimit: 2 # будет выполнять задачу пока не выполнит ее успешно , или пока не упрется в какие-либо лимиты. "2 попытки"
  activeDeadlineSeconds: 60 # в каком промежутке задача должна выполнится успешно "60 секунд"
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        args:
        -  /bin/sh
        -  -c
        -  date; echo Hello from the Kubernetes cluster
      restartPolicy: Never # в случае какой-либо проблемы контейнер не перезапустился
