apiVersion: apps/v1
kind: Deployment
metadata:
  name: me-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.12
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts: # подключение переменной из файла
        - name: config 
          mountPath: /etc/nginx/conf.d/ # создание файла для nginx
      volumes: # подключение файла
      - name: config
        configMap:
          name: my-configmap
...
